# Generated by Django 6.0.4 on 2026-04-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('departement', models.CharField(max_length=200)),
                ('poste', models.CharField(max_length=200)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
