# Generated by Django 6.0.4 on 2026-04-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Email',
            field=models.EmailField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
